<?php

class PasswordReset extends WireData implements Module
{
    private $scripts = "<script src='/site/modules/PasswordReset/js/password-reset.js'></script>";
    private $field = [];
    private $errorMessage;
    private $userEmail;

    public static function getModuleInfo() {
        return array(
            'title' => 'Password Reset',
            'summary' => 'Frontend password reset',
            'version' => 1,
            'autoload' => false,
            'singular' => true
        );
    }

    public function init() {
        $this->errorMessage = $this->session->errorMessage;
        $this->session->remove('errorMessage');

        if ($this->fieldname == 'name') {
            $this->field['name'] = 'name';
            $this->field['label'] = __('Username');
        } else {
            $field = wire('fields')->get($this->fieldname);
            $localizedLabel = "label" . wire('user')->language->id;
            $localizedLabel = $field->{$localizedLabel};
            $this->field['name'] = $field->name;
            $this->field['label'] = (!empty($localizedLabel)) ? $localizedLabel : $field->label;
        }
    }



    public function getScripts() {
        return $this->scripts;
    }


    private function getRequestForm($instructions = "") {
        // TODO : Probably implement urlSlashes check next line
        $form = "<form class='password-reset' action='request-key/' method='post'>" . PHP_EOL;
        $form .= "<div class='error'>{$this->errorMessage}</div>";
        $form .= "<label for='{$this->field['name']}-input'>{$this->field['label']}</label>" . PHP_EOL;
        $form .= "<input id='{$this->field['name']}-input' type='text' name='{$this->field['name']}' value=''>" . PHP_EOL;
        if (!empty($this->instructions)) $form .= "<div class='instructions'>{$this->instructions}</div>";
        $form .= "<input type='submit' value='" . __("Reset my password") . "'>";
        $form .= "</form>";

        return $form;
    }


    private function sendRequestEmail() {
        $email = wireMail();
        $email->from($this->emailAddress);
        $email->to($this->userEmail);
        $email->subject(__('Password reset'));
        $email->bodyHTML("<p>To reset your password, please click the following link:</p><p><a href='{$this->page->httpUrl}key/{$this->key}/'>{$this->page->httpUrl}key/{$this->key}/</a></p><p>If you did not request a password change, you can safely ignore this email.</p>"); // TODO : localize this
        $email->send();
    }


    private function generateKey()
    {
        // generate key
        $this->key = hash('sha256', openssl_random_pseudo_bytes(64));

        // set expiration time
        $date = new DateTime('now');
        $date->add(new DateInterval('PT24H'));
        $expiration = $date->getTimestamp();

        // get user or redirect back to form is user doesn't exist
        $credentials = $this->sanitizer->text($this->input->post($this->field['name']));
        if (!empty($credentials)) {
            $user = wire('users')->get("{$this->field['name']}={$this->input->post($this->field['name'])}");
            if (is_a($user, 'NullPage')) {
                $this->session->errorMessage = __('No user found matching those credentials.');
                $this->session->redirect($this->page->url);
            }
        } else {
            $this->session->errorMessage = __('The form must be filled.');
            $this->session->redirect($this->page->url);
        }

        $this->userEmail = $user->email;

        $keyPage = new Page();
        $keyPage->template = 'password-reset-request';
        $keyPage->parent_id = $this->page->id;
        $keyPage->title = $this->key;
        $keyPage->name = $this->key;
        $keyPage->passwordResetExpiration = $expiration;
        $keyPage->passwordResetUser = $user;
        $keyPage->save();
    }


    private function requestKeyIsValid() {
        if ($this->page->children('name='.$this->getKey())->count() !== 1) {
            $this->errorMessage = "<p class='error invalid'>".__('Invalid password reset key.')."</p>";
        } else if ($this->page->get('name='.$this->getKey())->passwordResetExpiration < time()) {
            $this->errorMessage = "<p class='error expired'>".__('Your password reset key expired.')."</p>";
            $this->deleteRequestKey();
        } else {
            return true;
        }
    }


    private function deleteRequestKey() {
        $key = $this->page->get('name='.$this->getKey())->delete();
    }


    private function getRequestKeyMessage() {
        $message = "<div class='password-reset request'><p>".__('An email containing a link allowing you to reset your password was sent to you.')."</p>";
        $message .= "<p>".__('This reset link will expire in 24 hours.')."</p></div>";
        return $message;
    }


    private function getKey() {
        if ($this->input->post('request-key') !== null) {
            $this->key = $this->input->post('request-key');
        } else {
            $this->key = $this->input->urlSegment2;
        }
        return $this->key;
    }


    private function getKeyPage() {
        return $this->page->get('name='.$this->getKey());
    }


    private function getResetForm() {
        if ($this->requestKeyIsValid() === true) {
        // TODO : Set default type to 'password' and add a checkbox to show it in clear
            $form = "<form class='password-reset reset-form' action='{$this->page->url}reset/' method='post'>" . PHP_EOL;
            $form .= "<label for='new-password'>".__('Please choose a new password')."</label>" . PHP_EOL;
            $form .= "<input id='new-password' type='password' name='new-password' value=''>" . PHP_EOL;
            $form .= "<label class='display-password'><input id='display-password' type='checkbox' name='display-password' value=''>".__('Show password')."</label>" . PHP_EOL;
            $form .= "<input id='request-key' type='hidden' name='request-key' value='".$this->getKey()."'>" . PHP_EOL;
            $form .= "<input type='submit' value='" . __("Reset my password") . "'>";
            $form .= "</form>";

            return $form;
        } else {
            // get returned error message
            return $this->errorMessage;
        }
    }


    private function resetPassword() {
        if ($this->requestKeyIsValid() === true) {
            $user = $this->getKeyPage()->passwordResetUser;
            $user->of(false);
            $user->pass = $this->sanitizer->text($this->input->post('new-password'));
            $user->save();

            $this->deleteRequestKey();

            return "<p>Your password was successfully reset.</p>";
        } else {
            return $this->errorMessage;
        }
    }


    public function controller() {
        $segment1 = ($this->input->urlSegment1);
        $segment2 = ($this->input->urlSegment2);

        if (empty($segment1)) {
            $this->session->requestKeySent = false;
            return $this->getRequestForm();
        } else if ($segment1 === 'request-key') {
            // generate key, send message and prevent requesting another key by accident or on refresh
            if ($this->session->requestKeySent !== true) {
                $this->generateKey();
                $this->sendRequestEmail();
                $this->session->requestKeySent = true;
                return $this->getRequestKeyMessage();
            } else {
                return $this->getRequestKeyMessage();
            }
        } else if ($segment1 === 'key' and empty($segment2)) {
            wire('session')->redirect($this->page->url);
        } else if ($segment1 === 'key' and !empty($segment2)) {
            return $this->getResetForm();
        } else if ($segment1 === 'reset') {
            return $this->resetPassword();
        }
    }


    public function ___install() {
        // password reset request template (the child storing requests)
        $expirationField = new Field();
        $expirationField->type = $this->modules->get('FieldtypeInteger');
        $expirationField->name = 'PasswordResetExpiration';
        $expirationField->save();

        $userField = new Field();
        $userField->type = $this->modules->get('FieldtypePage');
        $userField->name = 'PasswordResetUser';
        $userField->save();

        $requestFieldgroup = new Fieldgroup();
        $requestFieldgroup->name = 'password-reset-request';
        $requestFieldgroup->add($this->fields->get('title'));
        $requestFieldgroup->add($expirationField);
        $requestFieldgroup->add($userField);
        $requestFieldgroup->save();

        $requestTemplate = new Template();
        $requestTemplate->name = 'password-reset-request';
        $requestTemplate->fieldgroup = $requestFieldgroup;
        $requestTemplate->noChildren = true;
        $requestTemplate->save();


        // password reset template (the parent under which individual requests are stored)
        $fg = new Fieldgroup();
        $fg->name = 'password-reset';
        $fg->add($this->fields->get('title'));
        $fg->save();

        $passwordResetTemplate = new Template();
        $passwordResetTemplate->name = 'password-reset';
        $passwordResetTemplate->urlSegments(true);
        $passwordResetTemplate->fieldgroup = $fg;
        $passwordResetTemplate->childTemplates = [$requestFieldgroup->id];
        $passwordResetTemplate->childrenTemplatesID;
        $passwordResetTemplate->save();

        $requestTemplate->parentTemplates = [$passwordResetTemplate->id];
        $requestTemplate->save();
    }
}
